name: OpenChatKit
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - cudatoolkit=11.6.0
  - cupy=10.4.0
  - faiss-gpu=1.7.2
  - fastparquet=2023.2.0
  - nccl=2.12.12.1
  - pip=22.3.1
  - pyarrow=8.0.0
  - python=3.10.9
  - python-snappy=0.6.1
  - pytorch=2.0.0
  - pytorch-cuda=11.8
  - snappy=1.1.9
  - torchaudio=2.0.0
  - torchvision=0.15.0
  - pip:
      - accelerate==0.17.1
      - datasets==2.10.1
      - loguru==0.6.0
      - netifaces==0.11.0
      - transformers==4.27.4
      - wandb==0.13.10
      - zstandard==0.20.0
      - optimum==1.8.2
